name: dashpub_api
description: Shared models and API client for the Dashpub ecosystem.
version: 0.0.2
repository: https://github.com/canusdev/dashpub
issue_tracker: https://github.com/canusdev/dashpub/issues

topics:
  - api
  - client
  - pub
  - dashpub

environment:
  sdk: ^3.10.0

# Add regular dependencies here.
dependencies:
  # path: ^1.9.0
  json_annotation: ^4.8.1
  http: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^6.1.0
  test: ^1.24.0
