name: dashpub_cli
description: Official command-line companion tool for Dashpub.
version: 0.0.1

repository: https://github.com/canusdev/dashpub
issue_tracker: https://github.com/canusdev/dashpub/issues

topics:
  - cli
  - pub
  - tool
  - dashpub

executables:
  dashpub: dashpub

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.4.2
  http: ^1.1.0
  path: ^1.8.3
  archive: ^3.3.7
  yaml: ^3.1.2
  dashpub_api: ^0.0.1
  glob: ^2.1.3

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
  mocktail: ^1.0.0

dependency_overrides:
  dashpub_api:
    path: ../dashpub_api
